spring.application.name=myProject
server.port=8082

spring.data.mongodb.uri=mongodb+srv://sensanu1996_db_user:ntzm8ru2fAb9Jr4o@cluster0.jdwgxoq.mongodb.net/journaldb
spring.data.mongodb.auto-index-creation=true